/** @type {import('tailwindcss').Config} */
/* eslint-disable no-undef */
module.exports = {
    content: ['./src/**/*.{html,ts,css,scss,sass,less,styl}'],
    theme: {
        extend: {
            colors: {
                'primary-50': 'var(--primary-50)',
                'primary-100': 'var(--primary-100)',
                'primary-200': 'var(--primary-200)',
                'primary-300': 'var(--primary-300)',
                'primary-400': 'var(--primary-400)',
                'primary-500': 'var(--primary-500)',
                'primary-600': 'var(--primary-600)',
                'primary-700': 'var(--primary-700)',
                'primary-800': 'var(--primary-800)',
                'primary-900': 'var(--primary-900)',
                'primary-950': 'var(--primary-950)',
                'secondary-50': 'var(--secondary-50)',
                'secondary-100': 'var(--secondary-100)',
                'secondary-200': 'var(--secondary-200)',
                'secondary-300': 'var(--secondary-300)',
                'secondary-400': 'var(--secondary-400)',
                'secondary-500': 'var(--secondary-500)',
                'secondary-600': 'var(--secondary-600)',
                'secondary-700': 'var(--secondary-700)',
                'secondary-800': 'var(--secondary-800)',
                'secondary-900': 'var(--secondary-900)',
                'secondary-950': 'var(--secondary-950)',
                'accent-50': 'var(--accent-50)',
                'accent-100': 'var(--accent-100)',
                'accent-200': 'var(--accent-200)',
                'accent-300': 'var(--accent-300)',
                'accent-400': 'var(--accent-400)',
                'accent-500': 'var(--accent-500)',
                'accent-600': 'var(--accent-600)',
                'accent-700': 'var(--accent-700)',
                'accent-800': 'var(--accent-800)',
                'accent-900': 'var(--accent-900)',
                'accent-950': 'var(--accent-950)',
                'success-50': 'var(--success-50)',
                'success-100': 'var(--success-100)',
                'success-200': 'var(--success-200)',
                'success-300': 'var(--success-300)',
                'success-400': 'var(--success-400)',
                'success-500': 'var(--success-500)',
                'success-600': 'var(--success-600)',
                'success-700': 'var(--success-700)',
                'success-800': 'var(--success-800)',
                'success-900': 'var(--success-900)',
                'success-950': 'var(--success-950)',
                'warn-50': 'var(--warn-50)',
                'warn-100': 'var(--warn-100)',
                'warn-200': 'var(--warn-200)',
                'warn-300': 'var(--warn-300)',
                'warn-400': 'var(--warn-400)',
                'warn-500': 'var(--warn-500)',
                'warn-600': 'var(--warn-600)',
                'warn-700': 'var(--warn-700)',
                'warn-800': 'var(--warn-800)',
                'warn-900': 'var(--warn-900)',
                'warn-950': 'var(--warn-950)',
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [
        require('@tailwindcss/aspect-ratio'),
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('tailwindcss-elevation'),
    ],
}
